name: Release prerequisites
description: 'Checks whether the release-tag is mentioned in the changelog'

inputs:
  RELEASE_TAG:
    description: 'The tag of the release'
    required: true
  CHANGELOG_FILE:
    description: 'Location of the file that contains the changelog'
    required: false
    default: 'CHANGELOG.md'

outputs:
  RELEASE_BODY:
    description: 'Changelog section for this release'
    value: ${{ steps.release-body.outputs.RELEASE_BODY }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: '${{ inputs.RELEASE_TAG }}'

    - name: Check whether the release-tag is mentioned in changelog
      shell: bash
      run: |
        grep "${{ inputs.RELEASE_TAG }}" ${{ inputs.CHANGELOG_FILE }}

    - name: Generate release body
      id: release-body
      shell: bash
      run: |
        {
          echo 'RELEASE_BODY<<EOF'
          sed -n '/^## ${{ inputs.RELEASE_TAG }}/,/^## v.*/{//! s/^//p}' CHANGELOG.md | head -n -1
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Display release body
      shell: bash
      run: |
        echo "${{ steps.release-body.outputs.RELEASE_BODY }}"
