name: Release prerequisites

inputs:
  CHANGELOG_FILE:
    description: "Location of the file that contains the changelog"
    required: false
    default: "CHANGELOG.md"

outputs:
  RELEASE_BODY:
    description: "Changelog section for this release"
    value: ${{ steps.release-body.outputs.RELEASE_BODY }}

permissions:
  contents: write

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: "${{ github.ref_name }}"

    - name: Check whether the release-tag is mentioned in changelog
      shell: bash
      run: |
        grep "${{ github.ref_name }}" ${{ inputs.CHANGELOG_FILE }}

    - name: Generate release body
      id: release-body
      shell: bash
      run: |
        {
          echo 'RELEASE_BODY<<EOF'
          sed -n '/^## ${{ github.ref_name }}/,/^## v.*/{//! s/^//p}' CHANGELOG.md | head -n -1
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Display release body
      shell: bash
      run: |
        echo "${{ steps.release-body.outputs.RELEASE_BODY }}"

    - name: Delete version-tag when changelog doesn't contain information about it
      if: failure()
      shell: bash
      run: |
        git config --global user.name 'GithubActions'
        git config --global user.email 'githubactions@users.noreply.github.com'
        git push --delete origin ${{ github.ref_name }}
